# Generated by Django 4.1.13 on 2024-07-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatResponse',
        ),
    ]
